const page = document.body.dataset.page;
const nav = [["About","about.html"],["Academics","academics.html"],["Admissions","admissions.html"],["Facilities","facilities.html"],["Notices","notices.html"],["Gallery","gallery.html"],["Contact","contact.html"]];

document.querySelector("#site-header").innerHTML = `
  <div class="topbar"><div class="container"><span>Affiliated to SNDT Women’s University, Mumbai</span><div><a href="tel:+919850135878">+91 98501 35878</a><i></i><a href="contact.html">Contact</a></div></div></div>
  <header class="header"><div class="container header-row">
    <a class="brand" href="index.html"><span class="brand-mark">KG</span><span><b>Kasturba Gandhi Science Women’s College</b><small>Shirur (Kas.), Tal. Shirur, Dist. Beed</small></span></a>
    <button class="menu" aria-expanded="false" aria-label="Toggle navigation"><span></span><span></span><span></span></button>
    <nav aria-label="Main navigation">${nav.map(([label,url])=>`<a class="${page===url.slice(0,-5)?"active":""}" href="${url}">${label}</a>`).join("")}</nav>
  </div></header>`;

document.querySelector("#site-footer").innerHTML = `
  <footer class="footer"><div class="container footer-grid"><div><div class="footer-brand">Kasturba Gandhi Science Women’s College</div><p>Empowering women through accessible, meaningful science education and a supportive academic community.</p></div><div><h3>Explore</h3><a href="about.html">About the College</a><a href="academics.html">Academics</a><a href="admissions.html">Admissions</a><a href="notices.html">Notices</a></div><div><h3>Visit us</h3><p>Shirur (Kas.), Tal. Shirur,<br>Dist. Beed, Maharashtra</p><a href="tel:+919850135878">+91 98501 35878</a></div></div><div class="copyright"><div class="container">© ${new Date().getFullYear()} KGS Women’s College. All rights reserved.<span>Website content is illustrative.</span></div></div></footer>`;

const menu = document.querySelector(".menu");
menu.addEventListener("click",()=>{const open=document.querySelector("nav").classList.toggle("open");menu.setAttribute("aria-expanded",open)});

const hero = document.querySelector(".hero");
if(hero){
  const slides=[...document.querySelectorAll(".slide")],dots=document.querySelector(".dots"); let active=0,timer;
  slides.forEach((_,i)=>{const dot=document.createElement("button");dot.setAttribute("aria-label",`Show slide ${i+1}`);dot.onclick=()=>show(i);dots.append(dot)});
  const dotEls=[...dots.children];
  function show(i){active=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle("active",n===active));dotEls.forEach((d,n)=>d.classList.toggle("active",n===active));clearInterval(timer);timer=setInterval(()=>show(active+1),5500)}
  document.querySelector(".prev").onclick=()=>show(active-1);document.querySelector(".next").onclick=()=>show(active+1);show(0);
}

const pageData = {
  about:["About us","Rooted in purpose. Growing with every student.","A women-focused science college serving Shirur and the wider Beed region with accessible, student-centred higher education.",`
    <section class="section"><div class="container content-grid"><div><span class="eyebrow">Our story</span><h2>Science education within reach</h2><p class="lead">The college was established to expand access to higher education for women from Shirur and nearby communities.</p><p>Affiliated to SNDT Women’s University, Mumbai, the college aims to create a learning culture that values scientific inquiry, academic discipline and social responsibility.</p><p>Our students learn in a close-knit environment supported by teachers and resources that help them build a foundation for their future.</p></div><div class="content-image"><img src="images/e70cc897-813f-47b0-bdf0-d3ba006e8389.JPG" alt="College identity board"></div></div><div class="container values"><article><span class="eyebrow">Our vision</span><h3>Educated, confident and socially responsible women.</h3></article><article><span class="eyebrow">Our mission</span><h3>To make meaningful science education accessible and empowering.</h3></article></div></section>`],
  academics:["Academics","A practical path into the sciences","Explore our undergraduate programme, learning approach and the academic support available to every student.",`
    <section class="section"><div class="container"><div class="academic-card"><div><span class="eyebrow">Undergraduate programme</span><h2>Bachelor of Science (B.Sc.)</h2><p>A multi-year undergraduate degree affiliated to SNDT Women’s University. Intake and fee details are available from the college office.</p></div><div class="facts"><div><small>Level</small><b>Undergraduate</b></div><div><small>Duration</small><b>3 years*</b></div><div><small>Mode</small><b>Full-time</b></div><div><small>Eligibility</small><b>12th Science*</b></div></div></div><div class="subject-section"><span class="eyebrow">Subjects offered</span><h2>Explore the sciences</h2><div class="subject-grid"><article><b>01</b><h3>Physics</h3></article><article><b>02</b><h3>Chemistry</h3></article><article><b>03</b><h3>Mathematics</h3></article><article><b>04</b><h3>Botany</h3></article><article><b>05</b><h3>Zoology</h3></article><article><b>06</b><h3>Microbiology</h3></article></div></div><div class="steps"><article><b>01</b><h3>Concepts</h3><p>Build a clear theoretical foundation through guided classroom learning.</p></article><article><b>02</b><h3>Practice</h3><p>Connect theory with practical and computer-based exercises.</p></article><article><b>03</b><h3>Progress</h3><p>Receive guidance for further education and future opportunities.</p></article></div><p class="disclaimer">*Contact the college for the current university-approved programme structure and eligibility requirements.</p></div></section>`],
  admissions:["Admissions 2026–27","Begin your journey with us","Find the application steps, indicative eligibility and documents you may need. Final details will be published by the college.",`
    <section class="section"><div class="container admission-grid"><div><span class="eyebrow">How to apply</span><h2>Four simple steps</h2><div class="apply">${[["Check eligibility","Review the current eligibility criteria with the admissions office."],["Collect the form","Obtain the application form from the college office."],["Submit documents","Attach the required certificates, photographs and identity proof."],["Confirm admission","Complete verification and fee payment after selection."]].map((x,i)=>`<div><b>${i+1}</b><span><h3>${x[0]}</h3><p>${x[1]}</p></span></div>`).join("")}</div></div><aside class="document-box"><h3>Indicative document checklist</h3><ul><li>10th and 12th mark sheets</li><li>School / college leaving certificate</li><li>Passport-size photographs</li><li>Aadhaar or other identity proof</li><li>Caste / category certificate, if applicable</li><li>Migration certificate, if applicable</li></ul><a class="button gold" href="contact.html">Ask an admission question →</a><small>Final requirements may vary. Confirm with the college office.</small></aside></div></section>`],
  facilities:["Campus","Facilities that support participation","From digital learning to library resources, our campus supports practical study and student development.",`
    <section class="section"><div class="container facility-list">${[["Computer laboratory","76911961-5483-4fa9-977d-b9e98466ca1e.JPG"],["Library","1d371ac4-bac0-4d0b-a50e-1de1095061b1.JPG"],["Student activities","07a5796c-e8bf-4c5f-ae20-c92d1ae23c63.JPG"]].map((x,i)=>`<article><div class="facility-image"><img src="images/${x[1]}" alt="${x[0]}"></div><div><span class="eyebrow">0${i+1}</span><h2>${x[0]}</h2><p>Dedicated resources and an encouraging environment help students learn, collaborate and participate with confidence.</p></div></article>`).join("")}</div></section>`],
  notices:["Student desk","Notices & downloads","A central place for admission updates, academic announcements, forms and student information.",`
    <section class="section"><div class="container"><div class="notice-table">${[["20 Jul 2026","Admissions open for academic year 2026–27","Admissions"]].map(x=>`<div class="notice-row"><time>${x[0]}</time><span><b>${x[1]}</b><small>${x[2]} ·</small></span><button aria-label="Download placeholder notice">↓</button></div>`).join("")}</div></div></section>`],
  gallery:["Gallery","Life at KGS Women’s College","A glimpse of our classrooms, campus resources, activities and college community.",`
    <section class="section"><div class="container gallery">${["07a5796c-e8bf-4c5f-ae20-c92d1ae23c63.JPG","1d371ac4-bac0-4d0b-a50e-1de1095061b1.JPG","76911961-5483-4fa9-977d-b9e98466ca1e.JPG","39a656ed-8ec0-4efe-bc96-f62208374a26.JPG","6a7f770a-dc8e-4767-84bc-075c92866f42.JPG","9839421e-220f-462a-9d4a-339946bdbbe6.JPG","ba41758b-e372-4478-ad2b-bc0f68308e8e.JPG","c65e636f-324e-4613-9116-87ce41b72e9f.JPG","de345eb9-1a2c-4c0c-8703-2bb703250418.JPG"].map((src,i)=>`<figure class="${i===0||i===5?"wide":""}"><img loading="lazy" src="images/${src}" alt="College campus and activities ${i+1}"><figcaption>Campus life · 0${i+1}</figcaption></figure>`).join("")}</div></section>`],
  contact:["Contact","We’re here to help","Get in touch with the college for admissions, programme information or a campus visit.",`
    <section class="section"><div class="container contact-grid"><div><span class="eyebrow">Visit the college</span><h2>Kasturba Gandhi Science Women’s College</h2><div class="contact-details"><p><small>Address</small><b>Shirur (Kas.), Tal. Shirur,<br>Dist. Beed, Maharashtra</b></p><p><small>Phone</small><a href="tel:+919850135878">+91 98501 35878</a></p><p><small>Office hours</small><b>Monday–Saturday<br>10:00 AM–5:00 PM*</b></p></div><p class="disclaimer">*Placeholder office hours. Please call before visiting.</p></div><form class="contact-form" id="contact-form"><h3>Send an enquiry</h3><label>Name<input required placeholder="Your full name"></label><label>Phone or email<input required placeholder="How can we reach you?"></label><label>Message<textarea required rows="5" placeholder="Tell us how we can help"></textarea></label><button class="button gold" type="submit">Send enquiry →</button><small>Demo form — submission is not connected yet.</small></form></div></section>`]
};

if(pageData[page]){
  const [eyebrow,title,intro,content]=pageData[page];
  document.querySelector("#page-content").innerHTML=`<section class="page-hero"><div class="container"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${intro}</p></div></section>${content}`;
}
document.querySelector("#contact-form")?.addEventListener("submit",event=>{event.preventDefault();alert("Thank you. This demonstration form is not connected yet.")});
